# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=200)),
                ('user_access_token', models.CharField(max_length=200)),
                ('user_facebook_id', models.CharField(max_length=200)),
            ],
        ),
    ]
