# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url0', models.CharField(max_length=200)),
                ('photo_looks0', models.FloatField(default=50)),
                ('photo_url1', models.CharField(max_length=200)),
                ('photo_looks1', models.FloatField(default=50)),
                ('photo_url2', models.CharField(max_length=200)),
                ('photo_looks2', models.FloatField(default=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tinderuser',
            old_name='user_access_token',
            new_name='fb_auth_token',
        ),
        migrations.RenameField(
            model_name='tinderuser',
            old_name='user_facebook_id',
            new_name='fb_id',
        ),
        migrations.AddField(
            model_name='tinderuser',
            name='photo_percentage',
            field=models.FloatField(default=50),
        ),
    ]
